text_analyzer:
  description: >
    Execute comprehensive multi-layered linguistic analysis of the input text using advanced 
    natural language processing techniques. Perform sophisticated text decomposition through 
    sentence boundary detection, paragraph cohesion analysis, and topic modeling to create 
    semantically meaningful segments. Extract and catalog key phrases, terminology clusters, 
    domain-specific vocabulary, and semantic themes using latent semantic analysis and word 
    embedding techniques. Conduct detailed writing pattern analysis including syntactic parsing, 
    sentence complexity assessment, and identification of unique linguistic expressions and 
    author-specific stylistic markers. Apply comprehensive text preprocessing including 
    tokenization, lemmatization, named entity recognition, and part-of-speech tagging. Generate 
    structured text chunks optimized for similarity detection with overlapping n-grams, semantic 
    embeddings, and contextual vectors. Produce detailed metadata profiles including word 
    frequency distributions, readability metrics, lexical diversity scores, and linguistic 
    fingerprinting parameters for precise similarity matching.
  expected_output: >
    A comprehensive JSON structure containing: (1) Segmented text chunks with semantic boundaries 
    and overlapping n-grams, (2) Extracted key phrases and terminology clusters with relevance 
    scores, (3) Identified semantic themes with topic modeling results, (4) Detailed linguistic 
    fingerprint including syntactic patterns, stylistic markers, and writing complexity metrics, 
    (5) Comprehensive metadata profile with word frequency distributions, readability scores 
    (Flesch-Kincaid, Gunning Fog, SMOG), lexical diversity indices, average sentence length, 
    vocabulary richness measures, (6) Named entities and domain-specific terminology with 
    classifications, (7) Contextual embeddings and semantic vectors for each text segment, 
    (8) Structural analysis including paragraph cohesion scores and thematic transitions.
  agent: text_analyzer_agent
  output_file: output/text_segments.json

similarity_checker:
  description: >
    Conduct exhaustive multi-source similarity detection across diverse online repositories 
    including academic databases (PubMed, IEEE, ACM Digital Library), publication archives, 
    preprint servers, and web content using advanced comparison algorithms. Deploy sophisticated 
    text matching techniques including exact phrase matching, semantic similarity scoring, 
    paraphrasing detection, and cross-lingual plagiarism identification. Implement advanced 
    similarity detection methods including cosine similarity on TF-IDF vectors, BERT-based 
    semantic embeddings, fuzzy string matching algorithms, and n-gram overlap analysis. Detect 
    sophisticated plagiarism techniques such as synonym substitution, sentence reordering, 
    paraphrasing, translation-based plagiarism, and idea plagiarism through conceptual mapping. 
    Generate detailed similarity reports with precise percentage matches, confidence scores, 
    granular source attribution, exact match locations, and structural similarity assessments. 
    Document all discovered sources with complete metadata and flag potential plagiarism issues 
    with severity classifications and evidence-based reasoning.
  expected_output: >
    A comprehensive markdown report containing: (1) Executive summary with overall similarity 
    percentage and risk assessment, (2) Detailed similarity matrix with confidence scores for 
    each text segment, (3) Source documentation including URLs, publication dates, authors, 
    and accessibility status, (4) Exact match analysis with precise location mapping and 
    percentage overlap, (5) Paraphrasing detection results with semantic similarity scores, 
    (6) Cross-lingual plagiarism findings if applicable, (7) Severity classifications (minor, 
    moderate, severe) with evidence-based justifications, (8) Citation gap analysis identifying 
    missing attributions, (9) Structural similarity assessment comparing argument flow and 
    organization, (10) Visual similarity mappings and comparative analysis charts, (11) 
    Plagiarism technique identification (synonym substitution, reordering, etc.), (12) 
    Comprehensive bibliography of all detected sources with credibility assessments.
  context:
    - text_analyzer
  agent: similarity_checker_agent
  output_file: output/similarity_report.md

content_improvement:
  description: >
    Analyze comprehensive similarity reports and develop strategic, multi-faceted recommendations 
    for content enhancement and originality restoration. Provide detailed, actionable guidance 
    for rephrasing problematic sections while preserving core message, intent, and academic rigor. 
    Develop sophisticated rewriting strategies addressing different similarity types including 
    direct copying, close paraphrasing, structural mimicking, and conceptual overlap. Create 
    targeted improvement recommendations including sentence-level restructuring, vocabulary 
    diversification, argument reorganization, and narrative flow enhancement. Suggest alternative 
    phrasing options, synonyms, and linguistic variations while maintaining technical accuracy 
    and domain-specific terminology. Provide guidance on proper citation integration, quotation 
    usage, and attribution strategies. Develop comprehensive content enhancement plans including 
    structural improvements, rhetorical strengthening, clarity optimization, and originality 
    enhancement techniques. Offer specific before-and-after transformation examples and creative 
    approaches to presenting similar ideas uniquely while maintaining audience engagement and 
    academic standards.
  expected_output: >
    A detailed JSON document containing: (1) Strategic improvement roadmap with prioritized 
    action items and implementation timeline, (2) Section-by-section rewriting recommendations 
    with specific alternative phrasings and structural modifications, (3) Vocabulary enhancement 
    suggestions including synonym alternatives and technical term replacements, (4) Citation 
    integration strategies with proper attribution formats and quotation guidelines, (5) 
    Before-and-after transformation examples demonstrating originality enhancement techniques, 
    (6) Structural reorganization proposals including argument flow improvements and narrative 
    restructuring, (7) Quality assurance metrics and improvement tracking indicators, (8) 
    Risk mitigation strategies for high-similarity content areas, (9) Creative expression 
    alternatives for presenting similar concepts uniquely, (10) Academic integrity compliance 
    checklist with institutional policy alignment, (11) Audience engagement optimization 
    recommendations, (12) Technical accuracy validation guidelines for domain-specific content.
  context:
    - similarity_checker
  agent: content_improvement_agent

plagiarism_report:
  description: >
    Synthesize comprehensive, professional-grade plagiarism assessment reports integrating 
    findings from linguistic analysis, similarity detection, and content improvement recommendations 
    into cohesive, actionable documentation. Compile detailed multi-section reports featuring 
    executive summaries, methodology explanations, detailed findings with evidence, risk 
    assessments, and strategic remediation roadmaps tailored to different stakeholder needs. 
    Generate sophisticated analytical reports including quantitative similarity metrics, qualitative 
    assessment narratives, visual similarity mappings, and comparative analysis charts. Provide 
    comprehensive source documentation with complete bibliographic information, accessibility 
    verification, and credibility assessments. Create detailed plagiarism taxonomies categorizing 
    content overlap types including verbatim copying, close paraphrasing, structural imitation, 
    idea appropriation, and improper attribution. Develop risk-stratified recommendations with 
    priority matrices, implementation timelines, and success metrics. Include academic integrity 
    guidance, institutional policy compliance assessments, and legal risk evaluations where 
    applicable with clear, jargon-free explanations suitable for diverse audiences.
  expected_output: >
    A comprehensive markdown report containing: (1) Executive summary with overall plagiarism 
    risk assessment and key findings overview, and the overall or total score for plagiarism, (2) Methodology section explaining analysis 
    techniques and detection algorithms used, (3) Detailed findings section with evidence 
    documentation and similarity breakdowns, (4) Plagiarism taxonomy with categorized overlap 
    types and severity classifications, (5) Quantitative metrics including confidence intervals 
    and statistical significance measures, (6) Visual representations including similarity 
    heat maps, source distribution charts, and risk assessment matrices, (7) Complete source 
    bibliography with credibility ratings and accessibility status, (8) Risk-stratified 
    recommendations with priority levels and implementation timelines, (9) Academic integrity 
    compliance assessment with institutional policy alignment, (10) Legal risk evaluation 
    with potential implications and mitigation strategies, (11) Success metrics and progress 
    tracking indicators for remediation efforts, (12) Stakeholder-specific sections tailored 
    for students, educators, researchers, and administrators, (13) Evidence preservation 
    documentation for potential academic review processes, (14) Quality assurance validation 
    and reliability assessments for all findings.
  context:
    - content_improvement
    - similarity_checker
  agent: plagiarism_report_agent
  output_file: output/plagiarism_report.md
