from datetime import datetime


def format_report(report_content: str, filename: str = "Unknown") -> str:
    """Simple formatter to make reports more readable."""

    # Add a nice header
    header = f"""
# Plagiarism Analysis Report

**Document:** {filename}  
**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}  
**Status:** Analysis Complete

---

"""

    content = report_content
    # Make percentages bold
    import re

    content = re.sub(r"(\d+\.?\d*%)", r"**\1**", content)

    footer = f"""

---

*Report generated by AI Content Plagiarism Detection System*
"""

    return header + content + footer
